version: '3.1'

services:
  api:
    container_name: football-league-manager
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    networks:
      - app-net

networks: 
  app-net:
