version: '3.1'

services:
  api:
    container_name: football-league-manager
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    networks:
      - app-net
    depends_on:
      - mongo-db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    depends_on:
      - mongo-db
    networks:
      - app-net
  mongo-db:
    image: mongo:4.4.14
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - app-net

networks:
  app-net:
